/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOP;
import OOP.notes.Note;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author dom
 */
public class UI extends javax.swing.JFrame {

    private List<Note> mainNoteList = new ArrayList<Note>();
    DefaultListModel<Note> noteListModel = new DefaultListModel<Note>();
    int currentSelectionIndex = 0;
            
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        noteListModel.addElement(new Note());
        noteJList.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        notePane = new javax.swing.JSplitPane();
        noteSidePanel = new javax.swing.JPanel();
        newNoteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteJList = new javax.swing.JList<>();
        editPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTextEditorPane = new javax.swing.JEditorPane();
        noteTitleTextField = new javax.swing.JTextField();
        contactPane = new javax.swing.JSplitPane();
        noteList1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        editPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jTextField2 = new javax.swing.JTextField();
        calendarPanel = new javax.swing.JPanel();
        optionsPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyNotes");
        setBackground(new java.awt.Color(20, 18, 12));
        setForeground(java.awt.Color.black);
        setName("mainWindow"); // NOI18N

        notePane.setDividerLocation(200);
        notePane.setDividerSize(4);

        newNoteButton.setText("New");
        newNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNoteButtonActionPerformed(evt);
            }
        });

        noteJList.setModel(noteListModel);
        noteJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        noteJList.setToolTipText("");
        noteJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                noteJListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(noteJList);

        javax.swing.GroupLayout noteSidePanelLayout = new javax.swing.GroupLayout(noteSidePanel);
        noteSidePanel.setLayout(noteSidePanelLayout);
        noteSidePanelLayout.setHorizontalGroup(
            noteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noteSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(newNoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        noteSidePanelLayout.setVerticalGroup(
            noteSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noteSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newNoteButton)
                .addContainerGap())
        );

        notePane.setLeftComponent(noteSidePanel);

        noteTextEditorPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        noteTextEditorPane.setDoubleBuffered(true);
        noteTextEditorPane.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                noteTextEditorPaneCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(noteTextEditorPane);

        noteTitleTextField.setText("Untitled");
        noteTitleTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                noteTitleTextFieldCaretUpdate(evt);
            }
        });
        noteTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTitleTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteTitleTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noteTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        notePane.setRightComponent(editPanel);

        jTabbedPane1.addTab("Notes", notePane);

        contactPane.setDividerLocation(200);
        contactPane.setDividerSize(4);

        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout noteList1Layout = new javax.swing.GroupLayout(noteList1);
        noteList1.setLayout(noteList1Layout);
        noteList1Layout.setHorizontalGroup(
            noteList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noteList1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noteList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        noteList1Layout.setVerticalGroup(
            noteList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noteList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        contactPane.setLeftComponent(noteList1);

        jScrollPane4.setViewportView(jEditorPane2);

        jTextField2.setText("Untitled");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPanel1Layout = new javax.swing.GroupLayout(editPanel1);
        editPanel1.setLayout(editPanel1Layout);
        editPanel1Layout.setHorizontalGroup(
            editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        editPanel1Layout.setVerticalGroup(
            editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        contactPane.setRightComponent(editPanel1);

        jTabbedPane1.addTab("Notes", contactPane);

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        calendarPanelLayout.setVerticalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Calendar", calendarPanel);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Save your notes to a file");

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Load your notes from a file");

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options", optionsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNoteButtonActionPerformed
        noteListModel.addElement( new Note() );
    }//GEN-LAST:event_newNoteButtonActionPerformed

    private void noteTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTitleTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
        
    private void noteTextEditorPaneCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_noteTextEditorPaneCaretUpdate
        System.out.println("CARET UPDATE ~ Text");
        noteListModel.get(currentSelectionIndex).setDescription(noteTextEditorPane.getText());
    }//GEN-LAST:event_noteTextEditorPaneCaretUpdate

    private void noteJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_noteJListValueChanged
//        System.out.println(evt);
        System.out.println("SELECTION CHANGED");
        currentSelectionIndex = noteJList.getSelectedIndex();
        var selection = noteListModel.get(currentSelectionIndex);
        noteTextEditorPane.setText(selection.getDescription());
        noteTitleTextField.setText(selection.getTitle());
    }//GEN-LAST:event_noteJListValueChanged

    private void noteTitleTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_noteTitleTextFieldCaretUpdate
        System.out.println("CARET UPDATE ~ Title");
        noteListModel.get(currentSelectionIndex).setTitle(noteTitleTextField.getText());
    }//GEN-LAST:event_noteTitleTextFieldCaretUpdate

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView());
        
        var r = fileChooser.showSaveDialog(null);
        
        if (r == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
                FileOutputStream out = new FileOutputStream(fileChooser.getSelectedFile().getAbsolutePath());
                ObjectOutputStream s = new ObjectOutputStream(out);

                s.writeObject(noteListModel);
                s.flush();
                s.close();
            } catch (IOException e) { System.out.println("FAIL"); }
        }
        else
            System.out.println("the user cancelled the operation");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView());
        
        var r = fileChooser.showSaveDialog(null);
        
        if (r == JFileChooser.APPROVE_OPTION)
        {
            try {
                FileInputStream in = new FileInputStream(fileChooser.getSelectedFile().getAbsolutePath());
                ObjectInputStream s = new ObjectInputStream(in);

                noteListModel = (DefaultListModel<Note>) s.readObject();
                currentSelectionIndex = 0;
                noteJList.setModel(noteListModel);
                s.close();
            } catch (Exception e) { System.out.println(e); }
        }
        else
            System.out.println("the user cancelled the operation");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    
    // Manually written methods
    // void saveCurrentNote 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JSplitPane contactPane;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel editPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton newNoteButton;
    private javax.swing.JList<Note> noteJList;
    private javax.swing.JPanel noteList1;
    private javax.swing.JSplitPane notePane;
    private javax.swing.JPanel noteSidePanel;
    private javax.swing.JEditorPane noteTextEditorPane;
    private javax.swing.JTextField noteTitleTextField;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
